name: test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: grafana/grafonnet-lib
      - run: pip install jsonnet
      - run: ./tests.sh
